//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occasion_Table
    {
        public int OC_Id { get; set; }
        public string OC_Name { get; set; }
        public string OC_Description { get; set; }
        public string OC_Date { get; set; }
        public string OC_Time { get; set; }
    }
}
